project:
  type: book

book:
  title: "hormigas"
  author: "Julio Rivas"
  chapters:
     - index.qmd
     - chapters/conceptos.qmd
     - chapters/organizacion.qmd
     - chapters/principios.qmd
     - chapters/bbdd.qmd     
     - references.qmd
  appendices: 
    - chapters/appendix/license_cc.qmd
    
bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrbook
    titlepage: false
    papersize: a4
    toc-title: Indice
    toc: false
    toc-depth: 4
    number-sections: true



