project:
  type: book

book:
  title: "Las ciegas Hormigas Electricas"
  author: "Julio Rivas"
  chapters:
     - index.qmd
     - chapters/foundations.qmd
     - chapters/conceptos.qmd
     - chapters/organizacion.qmd
     - chapters/principios.qmd
     - chapters/bbdd.qmd     
     - references.qmd
  appendices: 
    - chapters/appendix/license_cc.qmd
    - chapters/appendix/e_mc2.qmd    
    - chapters/appendix/irr_algo.qmd    
    
bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrbook
    papersize: a4
    toc-title: Indice
    toc: true
    toc-depth: 3
    number-sections: true



